name: Prepare bundles
on:
  pull_request
env:
  DEST_REPO: michaltc/workspace-microapps-bundles
  BUNDLES_DIR: bundles
  BUNDLES_DIST_DIR: bundles-dist
  LINK_BUNDLES: https://github.com/michaltc/workspace-microapps-bundles/tree/master/bundles/
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v1

      - name: Maven modules cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build bundlegen
        run: mvn --batch-mode clean package

      - name: Execute bundlegen
        run: |
          rm -rf "${BUNDLES_DIST_DIR}"

          main_class="com.citrix.microapps.bundlegen.BundlegenMain"
          args="${BUNDLES_DIR} ${BUNDLES_DIST_DIR} ${LINK_BUNDLES}"

          mvn --batch-mode exec:java -pl bundlegen -Dexec.mainClass="${main_class}" -Dexec.args="${args}"
